# Generated by Django 3.1.5 on 2021-03-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210310_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='currency',
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='cents',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
