# Generated by Django 3.1.5 on 2021-03-15 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210311_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3),
        ),
    ]
